[build]
builder = "./build.sh"
watchPatterns = ["notes_frontend/**/*", "**/*.py", "staticfiles/**/*"]

[deploy]
startCommand = "gunicorn notes.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"