[build]
builder = "./build.sh"
watchPatterns = ["frontend/**/*", "backend/**/*", "staticfiles/**/*"]

[deploy]
startCommand = "gunicorn notes.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"